# Generated by Django 4.2.13 on 2024-06-24 12:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('booking_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BookingTable',
            new_name='TableBooking',
        ),
        migrations.RemoveField(
            model_name='signupmodel',
            name='phone_number',
        ),
        migrations.AlterField(
            model_name='tableinfo',
            name='seats',
            field=models.IntegerField(),
        ),
    ]
