# Generated by Django 4.2.13 on 2024-06-24 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signupmodel',
            name='phone_number',
        ),
    ]
