# Generated by Django 4.2.13 on 2024-06-24 10:26

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('booking_app', '0002_remove_signupmodel_phone_number'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BookingTable',
            new_name='TableBooking',
        ),
    ]
