# Generated by Django 4.2.13 on 2024-06-28 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking_app', '0003_remove_tableinfo_availability'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepagecontent',
            name='description',
        ),
        migrations.RemoveField(
            model_name='homepagecontent',
            name='title',
        ),
    ]
