# Generated by Django 4.2.13 on 2024-06-16 15:15

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('booking_app', '0004_alter_contactinformation_phone_number_bookingform'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BookingForm',
            new_name='BookingTable',
        ),
    ]
