# Generated by Django 4.2.13 on 2024-07-13 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_app', '0004_remove_homepagecontent_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tablebooking',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='tablebooking',
            name='special_requests',
            field=models.TextField(blank=True, default='', max_length=200, null=True),
        ),
    ]
