# Generated by Django 4.2.13 on 2024-06-17 11:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('booking_app', '0005_rename_bookingform_bookingtable'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookingtable',
            old_name='number_of_guest',
            new_name='number_of_guests',
        ),
        migrations.RemoveField(
            model_name='bookingtable',
            name='email',
        ),
        migrations.RemoveField(
            model_name='bookingtable',
            name='name',
        ),
        migrations.RemoveField(
            model_name='bookingtable',
            name='phone_number',
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('phone_number', models.CharField(max_length=20)),
                ('address', models.TextField(blank=True, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
