# Generated by Django 4.2.13 on 2024-06-20 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking_app', '0008_signupmodel_delete_signup'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SignupModel',
        ),
    ]
