# Generated by Django 4.2.13 on 2024-06-21 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_app', '0009_delete_signupmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='TableInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_number', models.PositiveIntegerField(unique=True)),
                ('capacity', models.PositiveIntegerField()),
                ('availability', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterField(
            model_name='bookingtable',
            name='number_of_guests',
            field=models.PositiveIntegerField(),
        ),
    ]
