# Generated by Django 4.2.13 on 2024-06-22 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking_app', '0010_tableinfo_alter_bookingtable_number_of_guests'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingtable',
            name='table',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='booking_app.tableinfo'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='menupagecontent',
            name='name',
            field=models.CharField(max_length=60),
        ),
    ]
