# Generated by Django 4.2.13 on 2024-06-22 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_app', '0011_bookingtable_table_alter_menupagecontent_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menupagecontent',
            name='name',
            field=models.CharField(max_length=300),
        ),
    ]
