# Generated by Django 4.2.13 on 2024-06-23 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_app', '0013_signupmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingtable',
            name='phone_number',
            field=models.CharField(blank=True, null=True),
        ),
    ]
