# Generated by Django 4.2.13 on 2024-06-23 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_app', '0014_bookingtable_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingtable',
            name='phone_number',
            field=models.CharField(blank=True, help_text='optional', max_length=15, null=True),
        ),
    ]
